/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.dudkomatt.androidcourse.chatproject.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param name 
 * @param pwd 
 */
@Serializable

data class LoginRequest (

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "pwd")
    val pwd: kotlin.String? = null

) {


}
