/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.dudkomatt.androidcourse.chatproject.model

import org.openapitools.client.models.MessageReceiveData

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param from 
 * @param to 
 * @param `data` 
 * @param time UNIX time
 */
@Serializable

data class MessageReceive (

    @SerialName(value = "id")
    val id: kotlin.String,

    @SerialName(value = "from")
    val from: kotlin.String,

    @SerialName(value = "to")
    val to: kotlin.String,

    @SerialName(value = "data")
    val `data`: MessageReceiveData,

    /* UNIX time */
    @SerialName(value = "time")
    val time: kotlin.String

) {


}
