/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.dudkomatt.androidcourse.chatproject.model

import org.openapitools.client.models.TextMessageSendData

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param from 
 * @param `data` 
 * @param to 
 * @param time UNIX time
 */
@Serializable

data class TextMessageSend (

    @SerialName(value = "from")
    val from: kotlin.String,

    @SerialName(value = "data")
    val `data`: TextMessageSendData,

    @SerialName(value = "to")
    val to: kotlin.String? = null,

    /* UNIX time */
    @SerialName(value = "time")
    val time: kotlin.String? = null

) {


}
